### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [buithuynhung/FromKotlinToJava#1]
1. Метод `toString()` Вашего bitset должен возвращать строку, в которой перечислены все, которые присутствуют (`check`) в множестве. У Вас он возвращает строку, в которой перечислены все числа от 0 до `cardinal`, независимо от содержимого bitset.
1. Методы `union`, `intersect` и `complement` должны работать в одном стиле: либо все возвращать новое множество, либо все менять объект, на котором вызваны. А в идеале вообще можно написать по 2 метода на каждую операцию, чтобы один возвращал новое множество, а второй менял объект.
1. `complement` лучше всё-таки реализовать с использованием побитовых операций.
1. В `addMassive` и `removeMassive` вызов `check` лишний: он вызывается внутри `addElement` и `removeElement`.

**Comment by buithuynhung** [comment]
Вам можно подсказать, как complement реализовать, если возвращать новое множество?
И мне можно только сделать 1 метод, в котором возвращаю  новое множество?

**Comment by buithuynhung** [comment]
Я исправила, но не уверена, что функция complement правильная(

**Comment by maximpetrov** [comment]
Как раз `complement` у Вас и так возвращал новое множество. Под побитовыми операциями я имел ввиду побитовое отрицание `~`, через которое у Вас Была реализована предыдущая версия `complement`, которую Вы мне показывали на занятии. Только в ней нужно было исправить ненужную инверсию неиспользуемых битов. Сейчас у Вас совсем неправильная версия `complement` хотя бы потому, что это должна быть операция над одним множеством, а не над двумя.

**Comment by buithuynhung** [comment]
Я сделала 2 задачу. Прошу вас посмотреть!

2017-03-16 10:58 GMT+03:00 Maxim Petrov <notifications@github.com>:
