### ISSUE TITLE
Замечания по заданию 2

### ISSUE THREAD

**Issue by maximpetrov** [buithuynhung/FromKotlinToJava#2]
1. Будет лучше, если методы по поиску файлов не будут статическими. То есть для поиска лучше создать объект класса (в котором будет храниться настройки поиска: каталог и необходимость искать в поддиректориях).
1. Зачем Вы переводите каталог поиска в строку и обратно? Передавайте и используйте его всегда как объект `File`.
1. Вы видимо всё-таки не совсем правильно поняли задание. Вам нужно не только проверить наличие файлов, но и вывести список их полных имен (с относительным или абсолютным путём по Вашему желанию). Будет совсем хорошо, если Вы не просто будете печатать эти имена по мере нахождения, а вернёте из метода класса как список, а уже в `main` напечатаете.
1. Два ваших метода по поиску файлов можно объединить в один, особенно, если Вы сделаете их не статическими.
1. Порядок опций не фиксирован, то есть `-r` может идти после `-d directory`.

**Comment by buithuynhung** [comment]
Значит, мне надо передавать и использовать файл и каталог как объект файл?

**Comment by buithuynhung** [comment]
Я уже исправила

**Comment by maximpetrov** [comment]
1. Отдельное поле `count` Вам не нужно, его можно получить как размер `result`.
1. Переименуйте `flagCmd`, чтобы было понятно что он хранит.
1. [Здесь](https://github.com/buithuynhung/FromKotlinToJava/blob/master/src/lesson2/FileSearch.java#L70-L78) можно обойтись без `if`.
1. Будет лучше, если методы `getResult` и `getCount` будут только возвращать результат, а не печатать его. Если хотите сделать методы, который печатают результаты на консоль, то сделайте их отдельными и назовите соответствующим образом.
1. Когда Вы делаете законченную программу, а не просто класс, нужно ловить исключения и выводить понятное сообщение об ошибке.

**Comment by buithuynhung** [comment]
Я исправила
